# Generated by Django 5.2.1 on 2025-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraudit', '0007_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
